#Funcion para incluir todos los scripts R

inicializa<-function()
{
source("actualizaPesos.R")
source("ajusteBayes.R")
source("calculaProbFlop.R")
source("calculaProbPreflop.R")
source("calculaProbPreflopIni.R")
source("calculaProbRiver.R")
source("calcularFuerzaMano.R")
source("calcularJugada.R")
source("calcularPotencial.R")
source("calculoOddMano.R")
source("calculoOddsBote.R")
source("calculoProbabilidadAccion.R")
source("cargaPesos.R")
source("cargaTriple.R")
source("chenFormula.R")
source("combinaMazo.R")
source("crearMazo.R")
source("descarteCartas.R")
source("descartePesosCarta.R")
source("descartePesosFlop.R")
source("descartePesosMano.R")
source("descarteTripleCarta.R")
source("descarteTripleFlop.R")
source("descarteTripleMano.R")
source("fijarMano.R")
source("fijarMesaFlop.R")
source("fijarMesaPostflop.R")
source("leerPesos.R")
source("leerTriple.R")
source("modificaPesos.R")
source("modificaTriple.R")
source("NumtoChar.R")
source("ordenarCartas.R")
source("PalotoChar.R")
source("pasar.R")
source("valorCartaAlta.R")
prob<-read.csv("prob_ini.csv",header=TRUE,row.names = NULL)
write.csv(prob,"prob.csv",row.names = FALSE)

}